baseURL = "https://follow.langitketujuh.id/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Tautan Bio | LangitKetujuh OS"
copyright = "2020-2023 | LangitKetujuh ID"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "LangitKetujuh"
  # image = "image/profile-langitketujuh.webp"

  links = [
    #{ link = { href = "styles/", text = "All the link styles", target = "_self" } },
    { link = { href = "https://langitketujuh.id", text = "Official Website", target = "_blank" } },
    { link = { href = "https://wiki.langitketujuh.id", text = "Wikipedia", target = "_blank" } },
    { link = { href = "https://langitketujuh.id/id/presskit", text = "Press Kit", target = "_blank" } },
    { mastodon = { href = "https://linux.social/@langitketujuh", text = "Mastodon" } },
    { telegram = { href = "https://t.me/langitketujuh_id", text = "Telegram" } },
    { facebook = { href = "https://facebook.com/langitketujuh.id", text = "Facebook" } },
    { instagram = { href = "https://instagram.com/langitketujuh.id", text = "Instagram" } },
    { telegram = { href = "https://t.me/langitketujuh_cs", text = "Telegram Admin" } },
    { whatsapp = { href = "https://wa.me/message/RN5NNCNHNEY6B1", text = "WhatsApp Admin" } },
    { telegram = { href = "https://t.me/langitketujuh_os", text = "Telegram Community" } },
    { facebook = { href = "https://facebook.com/groups/langitketujuh.os", text = "Facebook Community" } },
    { telegram = { href = "https://t.me/langitketujuh_bot", text = "Telegram Bot" } },
    { gitlab = { href = "https://gitlab.com/langitketujuh", text = "Gitlab Source Code", target = "_blank" } },
    { github = { href = "https://github.com/langitketujuh", text = "Github Source Code", target = "_blank" } },
    { link = { href = "https://langitketujuh.id/feedback/", text = "Feedback", target = "_blank" } },
    { email = "mailto:langitketujuh.id@pm.me" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.86.1"
